@startuml
skinparam classAttributeIconSize 0
hide methods
left to right direction

class Pharmacy {
    -Integer id
    -String designation
}


class Park {
    -Integer id
    -Integer maxCapacity
}

/'------------------------------------------------------------------------------------ '/


Pharmacy "1" -- "1..*" Park: has >

@enduml
