@startuml
autonumber

actor "Client" as CLI

participant ":AddProductToBasketUI" as UI
participant ":AddProductToBasketController" as CTRL
participant ":ProductsDB" as PDB
participant "products:List<Product>" as list
participant "p:Product" as P
participant ":UserSession" as US
participant "session:UserSession" as S
participant "u:User" as U
participant ":Utils" as UTILS





activate CLI
CLI -> UI: The client starts adding new product to basket
activate UI

UI -> CTRL: getProductsList()

activate CTRL

CTRL -> PDB : products = getProductsList()
activate PDB
deactivate PDB

deactivate CTRL


CLI <-- UI: the system shows the list of\n products and requests data (product ID, quantity)

deactivate UI

CLI -> UI: the user inserts the data

activate UI

UI -> CTRL: addProductToBasket(option, quantity)

activate CTRL

CTRL -> UTILS: p = getItemByOption(products, option)
activate UTILS
deactivate UTILS



CTRL -> US: session = getUserSession()

activate US
deactivate US

CTRL -> S: user = getUser()

activate S
deactivate S

CTRL -> U: email = getUserEmail()

activate U
deactivate U



CTRL -> PDB: addBasketProduct(email, id, quantity)

activate PDB
deactivate PDB

deactivate CTRL

CLI <-- UI: process finished

deactivate UI
deactivate CLI























@enduml
