@startuml
autonumber

actor "Client" as CLI

participant ":AddCreditCardUI" as UI
participant ":AddCreditCardController" as CTRL
participant "card:CreditCard" as CARD
participant ":UserSession" as US
participant "session:UserSession" as S
participant "user:User" as U
participant ":ClientDB" as DB


activate CLI
CLI -> UI: The client starts adding new credit card
activate UI

CLI <-- UI: requests data (number, cvv, expirate date)

deactivate UI

CLI -> UI: insert the data

activate UI

UI -> CTRL: newCreditCard(number, cvv, expirateDate)

activate CTRL



CTRL --> CARD**: create(number, cvv, expirateDate)

CTRL -> US: session = getUserSession()
activate US
deactivate US

CTRL -> S: user = getUser()

activate S
deactivate S
 CTRL -> U: email = getUserEmail()

 activate U
 deactivate U

 CTRL -> DB: newCreditCard(card, email)

 activate DB
 deactivate DB

 deactivate CTRL

 CLI <-- UI: process finished

 deactivate UI

 deactivate CLI






@enduml
