@startuml
autonumber
actor "Client" as CLB

activate CLB
CLB -> ":System" : starts adding credit card
activate ":System"
":System" --> CLB : requests data (number, cvv, expirate date)
deactivate ":System"
CLB -> ":System" : inserts the data

activate ":System"
":System" --> CLB : successful operation
deactivate ":System"

deactivate CLB
@enduml
