@startuml
autonumber
actor "Client" as CLB

participant ":System" as S

activate CLB
CLB -> S : starts checkout
activate S
S --> CLB : asks user if he want to use an\n existing credit card or to create another
deactivate S


alt existing card



CLB -> S : asks for existing credit cards

activate S

S --> CLB: shows a list of credit cards

deactivate S

CLB -> S: selects one credit card

activate S
deactivate S

end

alt create a new credit card

CLB -> S: wich to create new credit card

activate S
deactivate S


end



 alt if user has no NIF

 S --> CLB: requests data (NIF)


 CLB -> S: insert the NIF

 activate S
 deactivate S


 end

 S --> CLB: shows available credits for discount and asks \n how many credits the user wants to use


 CLB -> S: introduces credits
 activate S

 S --> CLB : process finished

 deactivate S

 deactivate CLB




@enduml
